version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rishi@123
      MYSQL_DATABASE: chatapp
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Rishi@123
      DB_NAME: chatapp
      JWT_SECRET: super-secret-jwt-key-change-this-in-production-123456789
      ENCRYPTION_KEY: message-encryption-key-change-this-too-987654321
      PORT: 5001

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
# my_sql_!@#$_not_correct_%$#@!_sno_iro-ur
